platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'FidoClient' do
  pod 'SwiftyJSON', '~> 4.0'
  pod 'BCryptSwift'

  target 'FidoClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
